# Generated by Django 2.2.24 on 2022-01-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerName', models.CharField(max_length=50)),
                ('accountNo', models.IntegerField(primary_key=True, serialize=False)),
                ('UPI_ID', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('balance', models.FloatField()),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
