# Generated by Django 2.2.24 on 2022-01-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField()),
                ('receiveraccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='home.Customer')),
                ('senderaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='home.Customer')),
            ],
        ),
    ]
